security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Jazzyweb\AulasMentor\NotasFrontendBundle\Entity\Usuario:
            algorithm:           sha512
            encode_as_base64:    true
            iterations:          1000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_PREMIUM: [ ROLE_REGISTRADO ]

    providers:
        in_memory:
            memory:
                users:
                   alberto:  { password: pruebas, roles: [ 'ROLE_REGISTRADO' ] }
                   maria: { password: pruebas, roles: [ 'ROLE_PREMIUM' ] }
                   miguel: { password: pruebas, roles: [ 'ROLE_ADMIN' ] }

        base_datos:
            entity: { class: JAMNotasFrontendBundle:Usuario, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        jamn_area_publica:
            pattern: ^/(registro|activar|tarifas|contratar|login$)
            security: false

        jamn_area_protegida:
            provider: base_datos
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/miespacio, roles: ROLE_PREMIUM }
        - { path: ^/administracion, roles: ROLE_ADMIN }
        - { path: ^/ roles: ROLE_REGISTRADO }