parameters:
#    jam_notas_frontend.example.class: Jazzyweb\AulasMentor\NotasFrontendBundle\Example

services:
#    jam_notas_frontend.example:
#        class: %jam_notas_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
